### ISSUE TITLE
書き込みに削除ボタンを追加したい

### ISSUE THREAD

**Issue by doektak09** [homahi/keijiban20180403#25]
これも他部分の修正が必要？

**Comment by kazuma1989** [comment]
そうだね。削除するにはAPIの改修が必要。

**Comment by kazuma1989** [comment]
現状のスコープ外としてラベルを設定。

**Comment by doektak09** [comment]
画面側とりあえず着手

**Comment by kazuma1989** [comment]
It's out of the scope so I'm closing it here, but feel free to comment or reopen the issue, thanks.
