### ISSUE TITLE
CREATE TABLE系のSQLが消えてる

### ISSUE THREAD

**Issue by homahi** [homahi/keijiban20180403#28]
keigiban -> keijibanにするときに間違って削除してない？

**Comment by ObayashiTatsunori** [comment]
node側でテーブル作成する処理も考慮したため、CREATETABLE系のSQLを削除した

**Comment by homahi** [comment]
これcloseして良いかな？

**Comment by ObayashiTatsunori** [comment]
クローズします

**Comment by kazuma1989** [comment]
エラーになります

**Comment by homahi** [comment]
エラーとはどこが？

**Comment by kazuma1989** [comment]
Unhandled rejection SequelizeConnectionError: the database system is startingup

Docker で起動すると、nodeが先に起動しすぎてDBが起動していない状態になってしまう。
SQL単体であると楽かも。
