### ISSUE TITLE
nodeサーバーの起動スクリプトが欲しいかも

### ISSUE THREAD

**Issue by homahi** [homahi/keijiban20180403#35]
nohupでバックグラウンドで立てるというだけでも良い気がするけど。

**Comment by kazuma1989** [comment]
@ipepi 手が空いてないならやりましょうか

**Comment by ipepi** [comment]
foreverモジュールで自動化設定。詳細な設定までしていないためエラーメッセージが出るがOS再起動後もNodejsが自動で立ち上がることを確認。
